url: https://vikasdhiman.info
theme: plainwhite
remote_theme:  samarsault/plainwhite-jekyll
title: Vikas Dhiman
author: Vikas Dhiman
description: Professional website
show_excerpts: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10


header_pages:
  - contact.md
  - publications/mypub.html


plugins:
  - jekyll-paginate
  - jekyll-seo-tag

plainwhite:
  name: Vikas Dhiman
  tagline: |
     Asst Prof @ UMaine
     Robotics, Autonomous Vehicles,
     Machine Learning

  sitemap: true

  navigation:
    - title: Contact
      url: "/contact"
    - title: Calendar
      url: https://calendar.google.com/calendar/embed?src=vikas.dhiman%40maine.edu&ctz=America%2FNew_York
    - title: Resume
      url: "/images/resume.pdf"
    - title: Scholar
      url: https://scholar.google.com/citations?user=6Pn0FGUAAAAJ&hl=en
    - title: Publications
      url: publications/mypub.html

  portfolio_image: images/mugshot-hyd-flowers.png
    

  social_links:
    github: wecacuee
    twitter: VikasDhimanR
    email: vikas.dhiman@maine.edu
