url: https://wecacuee.github.io
theme: plainwhite
remote_theme: thelehhman/plainwhite-jekyll
title: Vikas Dhiman
author: Vikas Dhiman
description: Professional website
show_excerpts: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10


header_pages:
  - about.md
  - publications/mypub.html


plugins:
  - jekyll-paginate
  - jekyll-seo-tag

plainwhite:
  name: Vikas Dhiman
  tagline: |
     Asst Prof @ ECE-UMaine
     Robotics, Autonomous Vehicles,
     Machine Learning

  navigation:
    - title: vikas.dhiman [@T] maine [D0T] edu
      url: "mailto:vikas.dhiman [@T] maine [D0T] edu"
    - title: Resume
      url: "/images/resume.pdf"
    - title: Scholar
      url: https://scholar.google.com/citations?user=6Pn0FGUAAAAJ&hl=en
    - title: PGP key
      url: http://keys.gnupg.net/pks/lookup?op=get&search=0xB111F9DBEFC3DD0E
    - title: Publications
      url: publications/mypub.html
    - title: Calendar
      url: https://calendar.google.com/calendar/u/0?cid=dmlrYXMuZGhpbWFuQG1haW5lLmVkdQ

  portfolio_image: images/mugshot-hyd-flowers.png
    

  social_links:
    github: wecacuee
    twitter: VikasDhimanR
